# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcFijPairwiseCpp <- function(ref_gen, alfreq1, alfreq2, Nloci, Nallele, n) {
    .Call('sgsR_calcFijPairwiseCpp', PACKAGE = 'sgsR', ref_gen, alfreq1, alfreq2, Nloci, Nallele, n)
}

calcFijPopCpp <- function(Mcij, Mdij, distance_intervals, genotype_data, ref_gen, Nloci, Nallele, Nind, Ngenecopies, Nperm, x_coord, y_coord) {
    .Call('sgsR_calcFijPopCpp', PACKAGE = 'sgsR', Mcij, Mdij, distance_intervals, genotype_data, ref_gen, Nloci, Nallele, Nind, Ngenecopies, Nperm, x_coord, y_coord)
}

calcAlleleFreqPop <- function(alleles_1, alleles_2, Nallele) {
    .Call('sgsR_calcAlleleFreqPop', PACKAGE = 'sgsR', alleles_1, alleles_2, Nallele)
}

calcAlleleFreqCppInd <- function(alleles_1, alleles_2, Nallele) {
    .Call('sgsR_calcAlleleFreqCppInd', PACKAGE = 'sgsR', alleles_1, alleles_2, Nallele)
}

calcPairwiseDist <- function(x, y, Nind) {
    .Call('sgsR_calcPairwiseDist', PACKAGE = 'sgsR', x, y, Nind)
}

findDIs <- function(Mdij, distance_intervals, Nind) {
    .Call('sgsR_findDIs', PACKAGE = 'sgsR', Mdij, distance_intervals, Nind)
}

findEqualDIs <- function(Mdij, distance_intervals, Nind) {
    .Call('sgsR_findEqualDIs', PACKAGE = 'sgsR', Mdij, distance_intervals, Nind)
}

summarizeDIs <- function(Mdij, Mcij, distance_intervals, Nind) {
    .Call('sgsR_summarizeDIs', PACKAGE = 'sgsR', Mdij, Mcij, distance_intervals, Nind)
}

